name: container

on: push

jobs:
  node-docker:
    runs-on: ubuntu-latest
    container:
      image: node:13.5.0-alpine3.10
    steps:
      - name: log node version details
        run: |
          node -v 
          cat /etc/os-release  