name: container

on: push

jobs:
  node-docker:
    runs-on: ubuntu-latest
    container:
      image: node:13.5.0-alpine3.10
    steps:
      - name: log node version details
        run: |
          node -v 
          cat /etc/os-release  

      - name: step with docker 
        uses: docker://node:12.14.1-alpine3.10
        with:
          entrypoint: "/bin/echo"
          args: "hellow world"

      - name: step with docker 2 
        uses: docker://node:12.14.1-alpine3.10
        with:
          entrypoint: /usr/local/bin/node
          args: -v

      - uses: actions/checkout@v1
      - name: RUn scipt 
        uses: docker://node:12.14.1-alpine3.10
        with:
          entrypoint: ./script.sh
          args: "some string"
              

  