name: Martrix WF  

on: push

jobs:
  node-version:
    strategy:
      matrix:
        os: [ubuntu-latest,windows-latest,macos-latest]
        node_ver: [6,7,8]
        include:
          - os: ubuntu-latest
            node_ver: 8
            is_ubuntu_8: true
        exclude:
          - os: ubuntu-latest
            node_ver: 6
    runs-on: ${{matrix.os}}
    env: 
      is_ubutn: ${{matrix.is_ubuntu_8}}
    steps:
      - name: nodee --version
        run: node -v 

      - uses: actions/setup-node@v1 
        with:   
          node-version: ${{matrix.node_ver}}

      - name: nodee --version
        run: |
          node -v
          echo $is_ubutn 

     