name: shell commands

on: [push]

jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: echo string
        run: echo "hello dear"

      - name: multiple line script
        run: |
          node -v
          npm -v  

      - name: python commands
        run: |
          import platform
          print(platform.processor())
        shell: python  
